-- This script populates the 'product' table with 10 sample records for an e-supermarket.
-- The 'id' column is omitted as it is auto-generated by the database.

-- Clear existing data to prevent duplicates if the script is run multiple times
TRUNCATE TABLE product RESTART IDENTITY;

-- Note the addition of the 'category' column in the INSERT statement
INSERT INTO product (name, description, price, quantity, category) VALUES
(
    'Organic Whole Milk',
    '1 Gallon of fresh, USDA certified organic whole milk from grass-fed cows.',
    5.99,
    120,
    'Dairy & Eggs'
),
(
    'Artisan Sourdough Bread',
    'A freshly baked loaf of classic sourdough bread with a perfectly crispy crust and soft interior.',
    4.50,
    80,
    'Bakery'
),
(
    'Hass Avocados',
    'Bag of 4 ripe and creamy Hass avocados, perfect for toast, salads, or guacamole.',
    6.29,
    200,
    'Produce'
),
(
    'Cage-Free Brown Eggs',
    'One dozen large, grade A, cage-free brown eggs from pasture-raised hens.',
    4.99,
    150,
    'Dairy & Eggs'
),
(
    'Boneless Chicken Breast',
    '1 lb of fresh, air-chilled boneless and skinless chicken breast. No antibiotics ever.',
    7.49,
    90,
    'Meat & Seafood'
),
(
    'Premium Basmati Rice',
    'A 5 lb bag of authentic, aged, long-grain premium basmati rice from the foothills of the Himalayas.',
    9.99,
    250,
    'Pantry'
),
(
    'Canned Diced Tomatoes',
    '28 oz can of organic diced tomatoes in tomato juice. Non-GMO and no salt added.',
    2.19,
    400,
    'Pantry'
),
(
    'Margherita Frozen Pizza',
    'A classic thin-crust margherita pizza with San Marzano tomatoes, fresh mozzarella, and basil.',
    8.99,
    110,
    'Frozen'
),
(
    'Natural Spring Water',
    'Pack of 24, 16.9 oz bottles of crisp and refreshing natural spring water.',
    5.49,
    300,
    'Beverages'
),
(
    'Fair Trade Dark Chocolate',
    'A 3.5 oz bar of 72% cacao dark chocolate. Rich, smooth, and ethically sourced.',
    3.79,
    180,
    'Snacks'
);